### ISSUE TITLE
Query showing

### ISSUE THREAD

**Issue by sangyoo91** [dburles/meteor-iron-router-query-array#1]
I'd like to show '?q=' when I set the value. 

```
Router.query.add('q');
```

This is what I have, but it returns

```
?q%5B%5D=undefined
```

**Comment by dburles** [comment]
hey @sangyoo91 this package is for manipulating query param arrays, if you're wanting to just add and remove string values maybe give this package a try https://atmospherejs.com/cottz/iron-query
